### ISSUE TITLE
Throws error when i try to request with params in the url

### ISSUE THREAD

**Issue by sridaradappt** [Skn0tt/nextjs-nestjs-integration-example#4]
I just created a simple get method which requests id and returns some data. It returns data when compiling

this is my code in app.controller.ts

```
@Get(':id')
  findOne(@Param('id') employeeId: string, @Query() query: any) {
      return Math.random() * 10;
  }
```

 error ] ./src/backend/app/app.controller.ts 11:10
Module parse failed: Unexpected character '@' (11:10)
File was processed with these loaders:
 * ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js
You may need an additional loader to handle the result of these loaders.
|   }
| 
>   findOne(@Param('id')
|   employeeId, @Query()
|   query) {
Error: Cannot find module for page: /api/[...catchAll]
    at pageNotFoundError (/Users/sridarmadurai/Projects/Workspace/nextjs-nestjs-integration-example/node_modules/next/dist/next-server/server/require.js:13:17)
    at Object.getPagePath (/Users/sridarmadurai/Projects/Workspace/nextjs-nestjs-integration-example/node_modules/next/dist/next-server/server/require.js:32:19)
    at DevServer.getPagePath (/Users/sridarmadurai/Projects/Workspace/nextjs-nestjs-integration-example/node_modules/next/dist/next-server/server/next-server.js:393:26)
    at DevServer.handleApiRequest (/Users/sridarmadurai/Projects/Workspace/nextjs-nestjs-integration-example/node_modules/next/dist/next-server/server/next-server.js:434:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Object.fn (/Users/sridarmadurai/Projects/Workspace/nextjs-nestjs-integration-example/node_modules/next/dist/next-server/server/next-server.js:366:37)
    at async Router.execute (/Users/sridarmadurai/Projects/Workspace/nextjs-nestjs-integration-example/node_modules/next/dist/next-server/server/router.js:132:32)
    at async DevServer.run (/Users/sridarmadurai/Projects/Workspace/nextjs-nestjs-integration-example/node_modules/next/dist/next-server/server/next-server.js:486:29)
    at async DevServer.handleRequest (/Users/sridarmadurai/Projects/Workspace/nextjs-nestjs-integration-example/node_modules/next/dist/next-server/server/next-server.js:138:20) {
  code: 'ENOENT'
}

Any Idea how to fix ?

**Comment by Skn0tt** [comment]
Could you provide a reproduction case? That would make it easier for me to debug :D

**Comment by jhlabs** [comment]
@sridaradappt you need to change the `.babelrc` file to the following and install the babel plugins:

```json
{
  "presets": ["next/babel"],
  "plugins": [
    "babel-plugin-transform-typescript-metadata",
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose" : true }]
  ]
}
```
